<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.10.11 setup script
 * Date: Tue, 20 Oct 2015 17:04:13 -0400
 */

/* Servers configuration */
$i = 0;

/* Server: JohnStrack.com [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'JohnStrack.com';
$cfg['Servers'][$i]['host'] = 'johnstrackcom.domaincommysql.com';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'john';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '5626abda759594.30772606';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>